caixa/urls.py
from django.contrib import admin
from django.urls import path
from .views import *


'''
1- Rota que será envocada no link se deixar vazio no link sera apenas localhost:8000/caixa,
2- Nome do Método DEF da minha VIEW ,
3- NAME= É Nome para a Rota que no caso uso por exemplo no link do MENU do html... exemplo href="{% url 'listar_entrada_saida' %}"
'''

urlpatterns = [
		path('listar_entrada_saida/',listar_entrada_saida, name='listar_entrada_saida'),
		path('cadastrar_entrada_saida/',cadastrar_entrada_saida, name='cadastrar_entrada_saida'),
		path('editar_entrada_saida/<int:id>', editar_entrada_saida, name='editar_entrada_saida'), # <int:id> isso quer dizer que estou passando o parametro no qual meu metodo da view precisa
		path('remover_entrada_saida/<int:id>', remover_entrada_saida, name='remover_entrada_saida'), # <int:id> isso quer dizer que estou passando o parametro no qual meu metodo da view precisa
		path('listar_entrada_saida_data/', listar_entrada_saida_data, name='listar_entrada_saida_data'),
		path('listar_entrada_saida_anomes/', listar_entrada_saida_anomes, name='listar_entrada_saida_anomes'),
		path('listar_especialidades_profissional/', listar_especialidades_profissional, name='listar_especialidades_profissional'),
		path('charts/', charts, name='charts'),
]

clinicaodontomed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ # onde aponto meu APP/diretorio/template e suas URLS que vai ser lida qdo eu digitar no browser
    path('admin/', admin.site.urls), # página do admin
    path('', include('home.urls')), # pág principal
    path('home/', include('home.urls')), # além da Pág Principal Aqui tenho a rota para o localhost:8000/teste ; localhost:8000/marcelo ...
    path('caixa/', include('caixa.urls')),
    path('profissional/', include('profissional.urls')),
    path('usuario/', include('usuario.urls')),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # optei pelo IF abaixo

if settings.DEBUG:
    #para funcionar os arquivos estaticos em DEBUG (Images, css, javascript, etc .)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *


urlpatterns = [
	path('', index, name='index'), # serve de Página Home e Logar Usuário no Sistema
	path('home/', index, name='index'), # serve de Página Home e Logar Usuário no Sistema
	# lê meu html dentro do template/teste/teste.html , na URLs principal do meu projeto eu dou um include na home.urls e é aqui que aponto para minha html teste e marcelo
	path('teste/', teste, name='teste'),
	path('marcelo/', marcelo, name='marcelo'),
]





# Dessa maneira preciso que esteja importado da seguinte maneira
# from . import views
# urlpatterns = [
# 	path('', index, name='index'),
# 	path('teste/', teste, name='teste'),
# 	path('marcelo/', marcelo, name='marcelo'),
# ]

caixa/models.py
from django.db import models

from django.core.exceptions import ValidationError
from django.utils.html import format_html
#from joinfield.joinfield import JoinField
import datetime

# Create your models here.

'''
@@@ fazer algo assim para que eu trafegue no link com o UUID e não com o id , isso por segurança !
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, UUIDField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
import uuid

class User(AbstractUser):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
'''

class EntradaSaida(models.Model):
		TP_ENTRADA = (
				('ENTRADA',u'Entrada'),
				('SAIDA',u'Saida'),
		)
		TP_CONVENIO = (
				('INTERODONTO',u'InterOdonto'),
				('ODONTOPREV',u'OdontoPrev'),
				('BRADESCO',u'Bradesco'),
				('PARTICULAR',u'Particular'),
		)
		TP_PAGAMENTO = (
				('CREDITO',u'Credito'),
				('DEBITO', u'Debito'),
				('DINHEIRO', u'Dinheiro'),
		)
		TP_CREDITO = (
				('APRAZO',u'A Prazo'),
		)
		TP_PORCENTAGEM = (
				('0.00',u'0.00%'),
				('2.68', u'2.68%'),
				('7.07', u'7.07%'),
				('8.51', u'8.51%'),
		)
		# id_entrada_saida = # Não preciso me preocupar com o campo ID o django cria sozinho e como primary key e auto incremento.
		#dt_movimentacao = models.DateField(blank=False, null=False) #auto_now_add=True) serve para auto preencher o campo com a a data e hora atual, mas esta dando pau
		dt_movimentacao = models.DateField(default=datetime.datetime.now, null=False, blank=False)
		profissional=models.CharField(verbose_name='Profissional',max_length=130,blank=True)
		paciente=models.CharField(verbose_name='Paciente',max_length=130,blank=True)
		qt_parcelas=models.IntegerField(verbose_name='Quantidade de Parcelas',default=0)
		valor_entr_saida=models.DecimalField(verbose_name='Valor',max_digits=14,decimal_places=2,default=0.00, blank=True)
		tp_entrada=models.CharField(verbose_name='Tipos de Entrada', max_length=10, choices=TP_ENTRADA)
		tp_convenio = models.CharField(verbose_name='Tipos de Convênios', max_length=30, choices=TP_CONVENIO, blank=True, null=True)
		tp_pagamento = models.CharField(verbose_name='Tipos de Pagamentos', max_length=30, choices=TP_PAGAMENTO, blank=True, null=True)
		tp_credito = models.CharField(verbose_name='Tipos de Créditos', max_length=20, choices=TP_CREDITO, blank=True, null=True)
		tp_porcentagem = models.CharField(verbose_name='Tipos de Porcentagens', max_length=10, choices=TP_PORCENTAGEM, default=0.00, blank=True, null=True)
		observacao = models.TextField(verbose_name='Observação',blank=True)
		motivo = models.CharField(verbose_name='Motivo da Entrada/Saída', max_length=150, blank=True)
		fkprofissional = models.ForeignKey('profissional.Profissionais',verbose_name='Profissional',related_name='qry_profissionais', on_delete=models.CASCADE)
		fkespecialidades = models.ForeignKey('profissional.Especialidades', verbose_name='Especialidades', related_name='qry_especialidades',null=True, blank=True, on_delete=models.CASCADE)

		class Meta:
				db_table = 'tb_om_entrada_saida' # definindo o nome da tabela, no caso não utilizei deixei o django fazer por mim
				verbose_name = 'Tipo de Entrada'#'Entrada/Saída'
				verbose_name_plural = 'Tipos de Entradas'
				ordering = ['dt_movimentacao']

		def calcula_desconto(self):
				if self.tp_porcentagem == None:
						return 0.0
				else:
						calculo = (float(self.valor_entr_saida) * float(self.tp_porcentagem)) / 100
						return round(calculo, 2)

		def calcula_totalLiquido(self):
				valor_total = float(self.valor_entr_saida) - self.calcula_desconto()
				return "{0:.2f}".format(valor_total)
		
		# Modificando o valor do campo usando html
		def desconto(self):
				return format_html(
						'<span style="color:#006400;">{}</span>',
						self.calcula_desconto(),
				)
		def total(self):
				return format_html(
						'<span style="color:#FF0000; font-weight: bold;">{}</span>',
						self.calcula_totalLiquido(),
				)
		def valor(self):
				return format_html(
						'<span style="color:#FF0000;">{}</span>',
						self.valor_entr_saida,
				)

	
		# Esse método estava salvando certo pelo /admin , mas pelo front estava dando problemas com o seguinte erro: "Cannot force an update in save() with no primary key."
		def save(self, force_insert=False, force_update=False, using=None,update_fields=None):
				self.paciente = self.paciente.upper()
				super(EntradaSaida, self).save()
		
		#  Validações
		def clean(self):
				# Validações para os tipos de Movimentações de Entradas
				if self.tp_entrada == 'Entrada':
						#if self.tp_convenio:
						if self.tp_convenio == None:
								raise ValidationError({'tp_convenio','Sendo uma ENTRADA, o campo Tipo de Convênio tem que ser preenchido'})

						#if self.paciente:
						self.paciente = self.paciente.strip()
						if len(self.paciente.split(' ')) < 2:
								raise ValidationError({'paciente':'Nome e Sobrenome do Paciente são queridos'})

				
				# Validações para os tipos de Movimentações de Saídas
				if self.tp_entrada == 'SAIDA':
						if self.motivo == '':
								raise ValidationError({'motivo':'Sendo uma SAÍDA é necessário especificar algum motivo'})
								
			
				#Validações que servem para as duas Movimentações
				if self.qt_parcelas < 0:
						raise ValidationError({'qt_parcelas': 'Quantidade de parcelas não pode ser menor que 0'})
				
				if (self.valor_entr_saida == 0.00) :
						raise ValidationError({'valor_entr_saida':'O Valor tem que ser maior que 0'})
						
				super().clean()
				
		def __str__(self):
				data = self.dt_movimentacao.strftime('%d/%m/%Y') # formatando a data
				texto = self.tp_entrada + ' de R$ ' + str(self.valor_entr_saida) + ' , Data do Movimento de: ' + data
				return texto

caixa/forms.py
from django import forms

from .models import EntradaSaida

from profissional.models import Profissionais

TP_ENTRADA = [
		('ENTRADA', u'Entrada'),
		('SAIDA', u'Saida'),
]
TP_CONVENIO = [
		('INTERODONTO', u'InterOdonto'),
		('ODONTOPREV', u'OdontoPrev'),
		('BRADESCO', u'Bradesco'),
		('PARTICULAR', u'Particular'),
]
TP_PAGAMENTO = [
		('CREDITO', u'Credito'),
		('DEBITO', u'Debito'),
		('DINHEIRO', u'Dinheiro'),
]
TP_CREDITO = [
		('APRAZO', u'A Prazo'),
]
TP_PORCENTAGEM = [
		('0.00', u'0.00%'),
		('2.68', u'2.68%'),
		('7.07', u'7.07%'),
		('8.51', u'8.51%'),
]


class EntradaSaidaForm(forms.ModelForm):
		# profissionais = forms.ModelChoiceField(queryset=Profissionais.objects.all())
		class Meta:
				model = EntradaSaida
				#fields = '__all__'
				fields = ['dt_movimentacao','profissional','paciente','qt_parcelas','valor_entr_saida','tp_entrada',
									'tp_convenio','tp_pagamento','tp_credito','tp_porcentagem','observacao','motivo',
									'fkprofissional','fkespecialidades']
				
				# todo: outra maneira de montar meu widget
				# widgets = {
				# 		'dt_movimentacao': forms.DateInput(attrs={'class': 'date-input'}),
				#
				# }
	
	
# todo: NÃO ESTA RODA ESSE CODIGO : Fazer funcionar essa classe onde monto meus widgtes de cada campo
class RawEntradaSaidaForm(forms.Form):
		dt_movimentacao = forms.DateField()
		profissional = forms.CharField()
		paciente = forms.CharField()
		qt_parcelas = forms.DecimalField()
		valor_entr_saida = forms.DecimalField(initial=0.0)
		tp_entrada = forms.ChoiceField(widget=forms.RadioSelect, choices=TP_ENTRADA,)
		tp_convenio = forms.ChoiceField(widget=forms.Select, choices=TP_CONVENIO,)
		tp_pagamento = forms.ChoiceField(widget=forms.Select, choices=TP_PAGAMENTO)
		tp_credito = forms.ChoiceField(widget=forms.Select, choices=TP_CREDITO)
		tp_porcentagem = forms.ChoiceField(widget=forms.Select, choices=TP_PORCENTAGEM)
		observacao = forms.TextInput(attrs={"placeholder": "Escreva alguma observação"})
		motivo = forms.CharField()
		fkprofissional = forms.ModelChoiceField(queryset=Profissionais.objects.all())
		fkespecialidades = forms.CharField()
		

templates/caixa/confirma_exclusao.html
{% extends 'adminlte/base.html' %}

{% block title %}
    Remoção de Entrada/Saída
{% endblock %}

{% block content %}
<div class="col-md-12">
  <div class="box box-danger">
    <div class="box-header">
      <h3 class="box-title">Tem certeza que deseja remover essa: {{ entrada_saida.tp_entrada }} ?</h3>

        <div class="card_body">
            <h5 class="card-title">{{ entrada_saida.dt_movimentacao }} </h5>
            <p class="card-text"> Valor Total: {{ entrada_saida.total }} </p>
            <hr>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Remover</button>
                <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Voltar</a>
            </form>
        </div>

    </div>
  </div>
</div>


{% endblock content %}

templates/caixa/form_entrada_saida.html
    {% extends 'adminlte/base.html' %}

{% load meus_filtros %}

{% block title %}
    Cadastro de Entrada/Saida
{% endblock %}

{% include 'adminlte/_scripts.html' %} <!-- Include para funcionar o JS -->


{% block content %}
<div class="box box-primary">
    <div class="box-header box-body">
        <h1 class="box-title">Cadastro de Entrada e Saídas</h1>
    </div>
</div>

<div class="box box-success">
    <div class="box-body">

        <form id="myForm" method="POST">

            {% csrf_token %}

            <div class="row">

                <div class="form-group col-md-2">
                    {{ form_entrada_saida.erros }}
                    <label>Dt Movimentação: </label>
                        {{ form_entrada_saida.dt_movimentacao|addclass:'form-control'}}
                </div>


                <div class="form-group col-md-3">
                    {{ form_entrada_saida.tp_entrada.erros }}
                    <label>Entrada/Saída: </label>
                        {{ form_entrada_saida.tp_entrada|addclass:'form-control' }}
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-8">
                    {{ form_entrada_saida.paciente.erros }}
                    <label>Nome do Paciente: </label>
                        {{ form_entrada_saida.paciente|addclass:'form-control' }}
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    {{ form_entrada_saida.fkprofissional.erros }}
                    <label>Profissional: </label>
                        {{ form_entrada_saida.fkprofissional|addclass:'form-control' }}
                </div>


                <!--ESPECIALIDADES -->
<!--                <div class="form-group col-md-2">-->
<!--                    {{ form_entrada_saida.fkespecialidades.erros }}-->
<!--                    <label>Especialidade: </label>-->
<!--                        {{ form_entrada_saida.fkespecialidades|addclass:'form-control' }}-->
<!--                </div>-->


                <div class="form-group col-md-4">
                    {{ form_entrada_saida.fkespecialidades.erros }}
                    <label>Especialidades:</label>
                    <select id="id_fkespecialidades" name="fkespecialidades" class="form-control">

                        {% if especialidade  %}
                            <option value="{{ especialidade.pk }}">{{ especialidade }}</option> <!-- Nesse IF Carrego o combo com a especialidade que foi salva no banco -->
                        {% else %}
                            <option>Primeiro escolha o Profissional</option>  <!-- Se por algum motivo esta vindo sem especialidade traz o texto dizendo para escolher -->
                        {% endif %}

                        {% for especialidade in id_fkespecialidades %}
                        <option value="{{ especialidade.pk }}">{{ especialidade }}</option> <!-- Esse FOR vai preencher o combo com as especialidades relacionadas com o profissional -->
                        {% endfor %}


                    </select>
                </div>

            </div>

            <div class="row">
                <div class="form-group col-md-12">
                {{ form_entrada_saida.motivo.erros }}
                <label>Motivo: </label>
                    {{ form_entrada_saida.motivo|addclass:'form-control' }}
                </div>
            </div>
            <div class="row">

                <div class="form-group col-md-1">
                    {{ form_entrada_saida.qt_parcelas.erros }}
                    <label>Parcelas: </label>
                        {{ form_entrada_saida.qt_parcelas|addclass:'form-control' }}
                </div>
                <div class="form-group col-md-3">
                    {{ form_entrada_saida.valor_entr_saida.erros }}
                    <label>Vlr Entrada: </label>
                        {{ form_entrada_saida.valor_entr_saida|addclass:'form-control' }}
                </div>
                <div class="form-group col-md-3">
                    {{ form_entrada_saida.tp_convenio.erros}}
                    <label>Convênio: </label>
                        {{ form_entrada_saida.tp_convenio|addclass:'form-control' }}
                </div>
            </div>
            <div class="row">

                <div class="form-group col-md-3">
                    {{ form_entrada_saida.tp_pagamento.erros }}
                    <label>Pagamento: </label>
                        {{ form_entrada_saida.tp_pagamento|addclass:'form-control' }}
                </div>
                <div class="form-group col-md-3">
                    {{ form_entrada_saida.tp_credito.erros }}
                    <label>Crédito: </label>
                        {{ form_entrada_saida.tp_credito|addclass:'form-control' }}
                </div>
                <div class="form-group col-md-2">
                    {{ form_entrada_saida.tp_porcentagem.erros }}
                    <label>Porcentagem: </label>
                        {{ form_entrada_saida.tp_porcentagem|addclass:'form-control' }}
                </div>
            </div>
            <div class="row">

                <div class="form-group col-md-12">
                    {{ form_entrada_saida.observacao.erros }}
                    <label>Observação: </label>
                        {{ form_entrada_saida.observacao|addclass:'form-control' }}
                </div>
            </div>

            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Salvar">
                <a href="{{request.META.HTTP_REFERER}}" class="btn btn-success">Cancelar</a>
            </div>

        </form>
    </div>
</div>


{% block js %}
<script>

/*
$(document).ready(function(){
        console.log($("#id_fkprofissional option:selected" ).val());
        let id_fkprofissional = $("#id_fkprofissional option:selected" ).val();
        console.log(id_fkprofissional)
        $.ajax({
            url: "{% url 'listar_especialidades_profissional' %}",
            type: 'GET',
            data: {
                id_fkprofissional: id_fkprofissional
            },
            success: function(response){
                $('#id_fkespecialidades').html(response)
            }
        })
});
*/

    $('#id_fkprofissional').change(function(){
        let id_fkprofissional = $(this).val();
        $.ajax({
            url: "{% url 'listar_especialidades_profissional' %}",
            type: 'GET',
            data: {
                id_fkprofissional: id_fkprofissional
            },
            success: function(response){
            console.log(response)
                $('#id_fkespecialidades').html(response)
            }
        })
    });



    $(function data() {
        $("#id_dt_movimentacao").datepicker({
            format : 'dd/mm/yyyy',
            autoclose : true,
        });
    });

</script>
{% endblock js %}

{% endblock content %}

templates/caixa/listar_entrada_saida.html
{% extends 'adminlte/base.html' %}

{% block title %}
    Lista de Entradas/Saidas
{% endblock %}

{% block content %}

<div class="row">
<div class="col-md-8">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Lista de Entradas e Saídas</h3>
        </div>
    </div>
</div>

<div class="col-md-2">
    <div class="widget-user-header bg-green">
        <div class="info-box-content">
            <span class="info-box-text">ENTRADAS NO MÊS</span>
            <span class="info-box-number">{{ total_mes_entrada }}</span>
        </div>
    </div>
</div>

<div class="col-md-2">
    <div class="widget-user-header bg-red">
        <div class="info-box-content">
            <span class="info-box-text">SAÍDAS NO MÊS</span>
            <span class="info-box-number">{{ total_mes_saida }}</span>
        </div>
    </div>
</div>
</div>

<!--Campo de pesquisa-->
<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            <div class="box-header">
        <!--        <div class="pull-left col-md-10">-->
        <!--            <h1 class="box-title">Filtros</h1>-->
        <!--        </div>-->

                <div class="form-group">
                    <div class="col-md-3">
                        <form action="{% url 'listar_entrada_saida_data' %}" method="GET">
                            <div class="input-group">
                                <div class="input-group-addon input-group margin">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                    <input type="text" placeholder="Pesquisa por Data Específica" class="form-control" id="datepicker_filter" name="datepicker_filter"
                                           data-toggle='#datepicker_filter1' readonly>

                                    <div class="input-group-btn">
                                        <button class="btn btn-info" id="btndata" type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <form action="{% url 'listar_entrada_saida_anomes' %}" method="GET">
                            <div class="input-group">
                                <div class="input-group-addon input-group margin">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                    <input type="text" placeholder="Pesquisa por Mês/Ano" class="form-control" id="datepicker_month_filter" name="datepicker_month_filter" readonly>
                                    <span class="input-group-btn">
                                        <button class="btn btn-info" id="btndatames" type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-body">
                <table id="myTableCaixa" class="table table-bordered table-hover" cellpadding="5" width="100%">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Entr/Saída</th>
                            <th>Profissional</th>
                            <th>Especialidade</th>
                            <th>Paciente</th>
                            <th>Motivo</th>
                            <th>Convênio</th>
                            <th>Pagamento</th>
                            <th>Créditos</th>
                            <th width="100px">VLR BRUTO</th>
                            <th>DESCONTO</th>
                            <th width="100px">VLR LIQ</th>
                            <th>AÇÔES</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for entrada_saida in entradas_saidas %}
                        <tr>
                            <td>{{ entrada_saida.dt_movimentacao }}</td>
                            <td>{{ entrada_saida.tp_entrada }}</td>
                            <td>{{ entrada_saida.fkprofissional }}</td>
                            <td>{{ entrada_saida.fkespecialidades|default_if_none:"" }}</td>
                            <td>{{ entrada_saida.paciente }}</td>
                            <td>{{ entrada_saida.motivo }}</td>
                            <td>{{ entrada_saida.tp_convenio|default_if_none:"" }}</td>
                            <td>{{ entrada_saida.tp_pagamento|default_if_none:"" }}</td>
                            <td>{{ entrada_saida.tp_credito|default_if_none:"" }}</td>
                            <td>{{ entrada_saida.valor }}</td>
                            <td>{{ entrada_saida.desconto }}</td>
                            <td>{{ entrada_saida.total }}</td>
                            <td class="dt-body-center" nowrap="">
                                <a class="btn btn-info" href="{% url 'editar_entrada_saida' entrada_saida.id %}">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a class="btn btn-danger" href="{% url 'remover_entrada_saida' entrada_saida.id %}">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                        <tfoot>
                                <!--  Esse primtio TR estou fazendo como se fosse um Header do Foot abaixo      -->
                                <tr style="background-color:#4682B4">
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th>Entrada + Saida </th>
                                <th>Tot Descontos </th>
                                <th>Ent+Saida - Desc</th>
                                <th></th>
                            </tr>

                            <tr style="background-color:#d3d3d3">
                                <th>TOTAL GERAL</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th style="color:#FF0000">R$ {{ total_bruto_final }}</th>
                                <th style="color:#006400">R$ {{ total_desconto_final }}</th>
                                <th style="color:#FF0000">R$ {{ total_liquido_final }}</th>
                                <th></th>
                            </tr>
                        </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
<div class="btn btn-outline-primary">
        <a href="{% url 'cadastrar_entrada_saida' %}"><input type="button" class="btn btn-primary mb3" value="Cadastrar Entrada Saida"></a>
</div>
<br>
<br>

{% block js %}
<script>
/*
 Estou definindo o DataTable e mais algumas configurações no arquivo _scripts dentro de /templates/adminlte/_scripts.html
    $(document).ready( function () {
        $('#myTableCaixa').DataTable(dsadsadsa);
    });
*/

    $(function data() {
        $("#datepicker_filter").datepicker({
            format : 'dd/mm/yyyy',
            autoclose : true,
        });
    });


    $(function data() {
        $("#datepicker_month_filter").datepicker({
            format : 'mm/yyyy',
            autoclose : true,
        })
    });

    /* Valida Campo Pesq Data Especifica */
    $("#btndata").on('click', function(){
        var dt = $("#datepicker_filter").val();
           if (dt == '') {
                alert('Preencher a Data Específica para Pesquisar')
                return;
            }
    });


    /* Valida Campo Pesq Mes Ano*/
    $("#btndatames").on('click', function(){
        var dt = $("#datepicker_month_filter").val();
           if (dt == '') {
                alert('Preencher a Data Mes/Ano para Pesquisar')
                return;
            }
    });


/* Fora de Uso
 Estava Usando para executar o evento do click do botão
    $("#btndata").on('click', function(env){
        env.preventDefault();
        var dt = $("#datepicker_filter").val();
        var url = "{% url 'listar_entrada_saida_data' %}";
        window.location.assign(url);
    });
*/
</script>

{% endblock js %}

{% endblock content %}